version: "3.9"
   
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - makemigrations
      - migration
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - makemigrations
  makemigrations:
    build: .
    command: python manage.py makemigrations
    volumes:
      - .:/code
    depends_on:
      - deliverymigrations
      - usersmigrations
      - feedbackmigrations
      - ordersmigrations
  deliverymigrations:
    build: .
    command: python manage.py makemigrations delivery
    volumes:
      - .:/code
  usersmigrations:
    build: .
    command: python manage.py makemigrations users
    volumes:
      - .:/code
  feedbackmigrations:
    build: .
    command: python manage.py makemigrations feedback
    volumes:
      - .:/code
  ordersmigrations:
    build: .
    command: python manage.py makemigrations orders
    volumes:
      - .:/code
